title:   Brodie Furgeson
logo: "/images/profile_image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Strategic-minded, versatile business intelligence analyst with broad business foundation aiming to make an impact at a data-driven organization, leveraging nearly a decade of experience in the consumer electronics accessories industry.
  <br><br><br>
  <a href="https://www.linkedin.com/in/brodie-furgeson-87a40720/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/bfurg#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/brodiefurgeson/Portfolio-BRODIE-FURGESON-eff18845026a45a0986091b44a76672b">View My Notion Portfolio</a>
  
theme: jekyll-theme-minimal   
 
